# Row variables — the juju materializer's surface. Values come from
# matrix/rows/<name>/juju.tfvars.json (generated by matrix/generate.mjs from
# the config model; do not hand-edit those). Defaults form the "bringup"
# shape used for the first apply and for smoke checks: local idp + MFA +
# verification, one provider, no add-on relations.

variable "kratos_config" {
  description = "Kratos charm config for the active row (the charm renders kratos.yaml from these)."
  type        = map(string)
  default = {
    enable_local_idp                 = "true"
    enforce_mfa                      = "true"
    enable_verification              = "true"
    enable_passwordless_login_method = "false"
    enable_oidc_webauthn_sequencing  = "false"
  }
}

variable "hydra_config" {
  description = "Hydra charm config for the active row."
  type        = map(string)
  default     = {}
}

variable "idp_dex_enabled" {
  description = "Whether the first (dex) IdP integrator publishes its provider (providers >= 1)."
  type        = bool
  default     = true
}

variable "idp_dex2_enabled" {
  description = "Whether the second (dex2) IdP integrator publishes its provider (providers >= 2)."
  type        = bool
  default     = false
}

variable "relate_tenant" {
  description = "tenant_service=present: relate tenant-service to login-ui (multi-tenancy) and kratos (registration/login webhooks)."
  type        = bool
  default     = false
}

variable "relate_hook" {
  description = "hook_service=present: relate hook-service to hydra (token hook)."
  type        = bool
  default     = false
}

variable "relate_uvs" {
  description = "user_verification=present: relate UVS to kratos (registration webhook + registration endpoint)."
  type        = bool
  default     = false
}

variable "ingress_hostname" {
  description = <<-EOT
    Hostname for the public traefik ingress. WebAuthn forbids IP-based RP IDs
    and kratos derives rp.id from this host, so webauthn rows need a real
    domain. Substrate identity, not a row dimension - set it per cluster in
    local.auto.tfvars (gitignored):
      - local workstation: "<LB-IP>.nip.io" (public wildcard DNS, zero setup;
        needs a resolver without DNS-rebind protection)
      - CI: any self-contained name, e.g. "iam-matrix.internal", plus one
        /etc/hosts line on the runner - no external DNS dependency
    Pin the metallb pool to a single IP so the name is known before the
    first apply. Default "" = bare-IP mode; webauthn journeys will not run.
  EOT
  type        = string
  default     = ""
}

variable "node_ip" {
  description = <<-EOT
    Address of the microk8s node that fronts the lane's NodePort services
    (dex 30556, mailslurper 30437). Substrate identity, not a row dimension -
    set it per cluster in local.auto.tfvars (gitignored); see
    local.auto.tfvars.example for how to obtain it.

    The dex issuer must be ONE URL that resolves identically from the kratos
    pods and from the host browser, which rules out both the in-cluster
    service DNS name and the ingress: node-IP:NodePort is the only form both
    sides agree on (the compose lane solves the same problem with Chromium
    host-resolver-rules). Consumed by the idp-dex/idp-dex2 issuer_url in
    main.tf and by manifests/dex.yaml.tpl via `make render-manifests`.

    No usable default: "" would render `http://:30556/dex`, so an unset value
    fails at plan time rather than deploying a broken IdP.
  EOT
  type        = string
  default     = ""

  validation {
    condition     = var.node_ip != ""
    error_message = "node_ip is unset: copy local.auto.tfvars.example to local.auto.tfvars and set this cluster's microk8s node address."
  }
}

# ─── Attach-mode surface (mode 3: configure an existing deployment) ─────────
# Clean mode leaves all of these at defaults and behaves exactly as before.

variable "model_name" {
  description = "Workload model name. Attach mode passes the discovered name; renaming a model is never intended."
  type        = string
  default     = "iam-matrix"
}

variable "core_model_name" {
  description = "Infra model name (traefik/postgres/certs/openfga)."
  type        = string
  default     = "iam-matrix-core"
}

variable "apps_present" {
  description = <<-EOT
    Which OPTIONAL apps exist in this deployment. Clean mode: all present
    (the lane's constant app set - rows toggle relations/config, never
    apps). Attach mode: discovered from the live model; a test run must
    never deploy new apps onto a cluster it does not own, and the runner
    refuses rows that require an absent app.
  EOT
  type = object({
    tenant_service            = optional(bool, true)
    hook_service              = optional(bool, true)
    user_verification_service = optional(bool, true)
    idp_dex                   = optional(bool, true)
    idp_dex2                  = optional(bool, true)
  })
  default = {}
}

variable "charm_revisions" {
  description = <<-EOT
    Charm revision pins per app key (hydra, kratos, login_ui,
    tenant_service, hook_service, user_verification_service, idp_dex,
    idp_dex2). Unset keys use the lane's tested pins. Attach mode passes
    the DISCOVERED deployed revisions - a test run must never refresh
    charms on a cluster it does not own.
  EOT
  type        = map(number)
  default     = {}
}

variable "kratos_image_revision" {
  description = "kratos oci-image resource revision. Lane pin = 434 (v26.2.0, migration runbook in main.tf). Attach mode passes the discovered resource revision."
  type        = number
  default     = 434
}

variable "manage_secrets" {
  description = "Whether this root owns the UVS salesforce secret. Attach mode sets false (secret values are write-only: applying would overwrite a foreign cluster's real credentials) and supplies uvs_salesforce_secret_id instead."
  type        = bool
  default     = true
}

variable "uvs_salesforce_secret_id" {
  description = "Existing salesforce-credentials secret id, required when manage_secrets = false and UVS is present."
  type        = string
  default     = ""
}

variable "cloud_name" {
  description = "Substrate cloud for the models (attach mode: discovered - an imported model's cloud block must match or terraform replaces the model, cascading replacement through every model_uuid). Empty = controller default (clean-mode behavior, unchanged)."
  type        = string
  default     = ""
}

variable "cloud_region" {
  description = "Substrate cloud region; only used when cloud_name is set."
  type        = string
  default     = ""
}

variable "login_ui_channel" {
  description = "login-ui charm channel (store origin only — local-origin charms are not a supported shape in any lane, decision D-2)."
  type        = string
  default     = "latest/edge"
}
